<?php
/**
* @file
* Module file for Welcome module
*/

/**
* Implements the hook_init().
*/
function welcome_init(){
    global $user;
}

/**
* Implements hook_user_login().
*/
function welcome_user_login(&$edit, $account) {

    dpm($account);
    $message = variable_get('welcome_message', 'welcome');
    $message_replaced = token_replace($message, array('user'=> $account));
    drupal_set_message(check_plain($message_replaced));
}


/**
* Implements hook_menu().
*/
function welcome_menu() {
    $items['admin/config/people/welcome'] = array(
        'title' => 'Welcome message configure',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('welcome_admin_settings'),
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'welcome.admin.inc',
    );

    return $items;
}
