<?php
/**
* @file
* Module file for Welcome module
*/

/**
* Implements the hook_init().
*/
function welcome_init(){
    global $user;
}

/**
* Implements hook_user_login().
*/
function welcome_user_login(&$edit, $account) {

    dpm($account);
    $message = variable_get('welcome_message', 'welcome');
    $message_replaced = token_replace($message, array('user'=> $account));
    drupal_set_message(check_plain($message_replaced));
}


/**
* Implements hook_menu().
*/
function welcome_menu() {
    $items['admin/config/people/welcome'] = array(
        'title' => 'Welcome message configure',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('welcome_form'),
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
* Implements hook_form().
* Admin form to configurable welcome Message
*/
function welcome_form($form, &$form_date) {
    $form['welcome_message'] = array(
        '#type'  => 'textarea',
        '#title' => t('Welcome message'),
        '#rows'  => 5,
        '#required' => TRUE,
        '#default_value' => variable_get('welcome_message', 'welcome'),
    );

    return system_settings_form($form);
}
