<?php
// $Id$
/**
* @file
* Lets users add privae annotations to nodes.
* Adds a text field when a node is displayed
* So that authenticated users may make nodes.
*/

/**
* Implementing of hook_menu().
*/

function annotate_menu() {
    $items['admin/settings/annotate'] = array(
            'title' => 'Annotation Settings',
            'description' => 'Change how annotations behave.',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('annotate_admin_settings'),
            'access arguments' => array('administer site configuration'),
            'type' => MENU_NORMAL_ITEM,
            'file' => 'annotate.admin.inc',
    );

    return $items;
}
